### ISSUE TITLE
EPIPE Unhandled error event

### ISSUE THREAD

**Issue by luigibertolucci** [dmcquay/imagesquish#16]
Hi,

I've been trying to test it Imagesquish but I can't seem to get it working.

It's giving me this error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
error: Forever detected script exited with code: 8

The url is well formatted and it is calling Imagesquish.
All the configuration seems correct.
I'm calling a server that has the image and that image does exist in the server.
I've been googling but can't find any conclusive reason for why this is happening.

Please help.

Thanks

**Comment by dmcquay** [comment]
No movement in this in a long time and I am officially removing support for uploads.
